//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré par un outil.
//     Version du runtime :4.0.30319.42000
//
//     Les modifications apportées à ce fichier peuvent provoquer un comportement incorrect et seront perdues si
//     le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Nebular.Bot.Properties {
    using System;
    
    
    /// <summary>
    ///   Une classe de ressource fortement typée destinée, entre autres, à la consultation des chaînes localisées.
    /// </summary>
    // Cette classe a été générée automatiquement par la classe StronglyTypedResourceBuilder
    // à l'aide d'un outil, tel que ResGen ou Visual Studio.
    // Pour ajouter ou supprimer un membre, modifiez votre fichier .ResX, puis réexécutez ResGen
    // avec l'option /str ou régénérez votre projet VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Retourne l'instance ResourceManager mise en cache utilisée par cette classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Nebular.Bot.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Remplace la propriété CurrentUICulture du thread actuel pour toutes
        ///   les recherches de ressources à l'aide de cette classe de ressource fortement typée.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;SKILLS&gt;
        ///  &lt;SKILL&gt;
        ///    &lt;nombre&gt;Alambique&lt;/nombre&gt;
        ///    &lt;gfx&gt;7019&lt;/gfx&gt;
        ///    &lt;caminable&gt;false&lt;/caminable&gt;
        ///    &lt;habilidades&gt;23&lt;/habilidades&gt;
        ///    &lt;recolectable&gt;false&lt;/recolectable&gt;
        ///  &lt;/SKILL&gt;
        ///  &lt;SKILL&gt;
        ///    &lt;nombre&gt;Arce&lt;/nombre&gt;
        ///    &lt;gfx&gt;7504&lt;/gfx&gt;
        ///    &lt;caminable&gt;false&lt;/caminable&gt;
        ///    &lt;habilidades&gt;37&lt;/habilidades&gt;
        ///    &lt;recolectable&gt;true&lt;/recolectable&gt;
        ///  &lt;/SKILL&gt;
        ///  &lt;SKILL&gt;
        ///    &lt;nombre&gt;Arroz&lt;/nombre&gt;
        ///    &lt;gfx&gt;7550&lt;/gfx&gt;
        ///    &lt;caminable&gt;true&lt;/caminable&gt;
        ///    &lt;habilidades&gt;159&lt;/hab [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string interactivos {
            get {
                return ResourceManager.GetString("interactivos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;HECHIZOS&gt;
        ///  &lt;HECHIZO ID=&quot;1&quot;&gt;
        ///    &lt;NOMBRE&gt;Armadura Incandescente&lt;/NOMBRE&gt;
        ///    &lt;NIVEL NIVEL=&quot;1&quot; COSTE_PA=&quot;2&quot; RANGO_MINIMO=&quot;0&quot; RANGO_MAXIMO=&quot;0&quot; LANZ_EN_LINEA=&quot;FALSE&quot; NECESITA_VISION=&quot;FALSE&quot; NECESITA_CELDA_LIBRE=&quot;FALSE&quot; RANGO_MODIFICABLE=&quot;FALSE&quot; MAX_LANZ_POR_TURNO=&quot;0&quot; MAX_LANZ_POR_OBJETIVO=&quot;0&quot; COOLDOWN=&quot;5&quot;&gt;
        ///      &lt;EFECTO TIPO=&quot;265&quot; COOLDOWN=&quot;4&quot; OBJETIVO=&quot;-1&quot; ZONA=&quot;Cc&quot; ES_CRITICO=&quot;FALSE&quot; /&gt;
        ///      &lt;EFECTO TIPO=&quot;265&quot; COOLDOWN=&quot;4&quot; OBJETIVO=&quot;-1&quot; ZONA=&quot;Cc&quot; ES_CRITICO=&quot;TRUE&quot; /&gt;
        /// [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string lista_hechizos {
            get {
                return ResourceManager.GetString("lista_hechizos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à &lt;?xml version=&quot;1.0&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;OFICIOS&gt;
        ///	&lt;OFICIO&gt;
        ///		&lt;id&gt;1&lt;/id&gt;
        ///		&lt;nombre&gt;Base&lt;/nombre&gt;
        ///	&lt;/OFICIO&gt;
        ///	&lt;OFICIO&gt;
        ///		&lt;id&gt;2&lt;/id&gt;
        ///		&lt;nombre&gt;Leñador&lt;/nombre&gt;
        ///	&lt;/OFICIO&gt;
        ///	&lt;OFICIO&gt;
        ///		&lt;id&gt;11&lt;/id&gt;
        ///		&lt;nombre&gt;Forjador de espadas&lt;/nombre&gt;
        ///	&lt;/OFICIO&gt;
        ///	&lt;OFICIO&gt;
        ///		&lt;id&gt;13&lt;/id&gt;
        ///		&lt;nombre&gt;Escultor de arcos&lt;/nombre&gt;
        ///	&lt;/OFICIO&gt;
        ///	&lt;OFICIO&gt;
        ///		&lt;id&gt;14&lt;/id&gt;
        ///		&lt;nombre&gt;Forjador de martillos&lt;/nombre&gt;
        ///	&lt;/OFICIO&gt;
        ///	&lt;OFICIO&gt;
        ///		&lt;id&gt;15&lt;/id&gt;
        ///		&lt;nombre&gt;Zapatero&lt;/nombre&gt;
        ///	&lt;/OFICIO&gt;
        ///	&lt;OFICIO&gt;
        ///		&lt;id&gt;16&lt;/id&gt;
        ///		&lt;nombre&gt;Joyero&lt;/nombre&gt;
        ///	&lt;/OFICIO [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string oficios {
            get {
                return ResourceManager.GetString("oficios", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///  &quot;1,-1&quot;: [
        ///    100,
        ///    101,
        ///    36,
        ///    692
        ///  ],
        ///  &quot;12,-7&quot;: [
        ///    1000,
        ///    1001,
        ///    1002,
        ///    1003,
        ///    1042,
        ///    1048,
        ///    999
        ///  ],
        ///  &quot;-66,-102&quot;: [
        ///    10000
        ///  ],
        ///  &quot;-67,-102&quot;: [
        ///    10001
        ///  ],
        ///  &quot;-67,-101&quot;: [
        ///    10002
        ///  ],
        ///  &quot;-68,-101&quot;: [
        ///    10003
        ///  ],
        ///  &quot;-68,-100&quot;: [
        ///    10004
        ///  ],
        ///  &quot;-69,-100&quot;: [
        ///    10005
        ///  ],
        ///  &quot;-69,-99&quot;: [
        ///    10006
        ///  ],
        ///  &quot;-69,-98&quot;: [
        ///    10007
        ///  ],
        ///  &quot;-69,-97&quot;: [
        ///    10008
        ///  ],
        ///  &quot;-68,-97&quot;: [
        ///    10009
        ///  ],
        ///  &quot;-68,-96&quot;: [
        ///    1 [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string PosToMapIDs {
            get {
                return ResourceManager.GetString("PosToMapIDs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Recherche une chaîne localisée semblable à {
        ///  &quot;8049&quot;: {
        ///    &quot;276&quot;: { &quot;ActionsArgs&quot;: &quot;8036,303&quot;, &quot;Conditions&quot;: false },
        ///    &quot;456&quot;: { &quot;ActionsArgs&quot;: &quot;8050,37&quot;, &quot;Conditions&quot;: false },
        ///    &quot;202&quot;: { &quot;ActionsArgs&quot;: &quot;8062,175&quot;, &quot;Conditions&quot;: false },
        ///    &quot;26&quot;: { &quot;ActionsArgs&quot;: &quot;8048,447&quot;, &quot;Conditions&quot;: false },
        ///    &quot;16&quot;: { &quot;ActionsArgs&quot;: &quot;8048,437&quot;, &quot;Conditions&quot;: false }
        ///  },
        ///  &quot;8050&quot;: {
        ///    &quot;22&quot;: { &quot;ActionsArgs&quot;: &quot;8049,441&quot;, &quot;Conditions&quot;: false },
        ///    &quot;160&quot;: { &quot;ActionsArgs&quot;: &quot;8037,187&quot;, &quot;Conditions&quot;: false },
        ///    &quot;318&quot;: { &quot;ActionsArgs&quot;: &quot;8063, [le reste de la chaîne a été tronqué]&quot;;.
        /// </summary>
        internal static string ScriptedCell {
            get {
                return ResourceManager.GetString("ScriptedCell", resourceCulture);
            }
        }
    }
}
